//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "BaseStructWithInterface.Generated.h"


#include "BaseStructWithInterface_Unknown.Generated.h"

#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace org.example {
// companion
// constants
// initializer
void BaseStructWithInterface::initialize()
{
}
// primary ctor
// secondary constructor
// default ctors and dtors
BaseStructWithInterface::BaseStructWithInterface()
{
    initialize();
}
// reader
rd::Wrapper<BaseStructWithInterface> BaseStructWithInterface::readUnknownInstance(rd::SerializationCtx& ctx, rd::Buffer & buffer, rd::RdId const& unknownId, int32_t size)
{
    int32_t objectStartPosition = buffer.get_position();
    auto unknownBytes = rd::Buffer::ByteArray(objectStartPosition + size - buffer.get_position());
    buffer.read_byte_array_raw(unknownBytes);
    BaseStructWithInterface_Unknown res{unknownId, unknownBytes};
    return rd::Wrapper<BaseStructWithInterface_Unknown>(std::move(res));
}
// writer
// virtual init
// identify
// getters
// intern
// equals trait
// equality operators
bool operator==(const BaseStructWithInterface &lhs, const BaseStructWithInterface &rhs) {
    if (lhs.type_name() != rhs.type_name()) return false;
    return lhs.equals(rhs);
}
bool operator!=(const BaseStructWithInterface &lhs, const BaseStructWithInterface &rhs){
    return !(lhs == rhs);
}
// hash code trait
size_t BaseStructWithInterface::hashCode() const noexcept
{
    size_t __r = 0;
    return __r;
}
// type name trait
std::string BaseStructWithInterface::type_name() const
{
    return "BaseStructWithInterface";
}
// static type name trait
std::string BaseStructWithInterface::static_type_name()
{
    return "BaseStructWithInterface";
}
// polymorphic to string
std::string BaseStructWithInterface::toString() const
{
    std::string res = "BaseStructWithInterface\n";
    return res;
}
// external to string
std::string to_string(const BaseStructWithInterface & value)
{
    return value.toString();
}
}

#ifdef _MSC_VER
#pragma warning( pop )
#endif

