//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.11.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "BaseClass.Generated.h"


#include "BaseClass_Unknown.Generated.h"

#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace org.example {
// companion
// constants
// initializer
void BaseClass::initialize()
{
}
// primary ctor
BaseClass::BaseClass(int32_t baseField_) :
rd::IPolymorphicSerializable(), rd::RdBindableBase()
,baseField_(std::move(baseField_))
{
    initialize();
}
// secondary constructor
// default ctors and dtors
// reader
rd::Wrapper<BaseClass> BaseClass::readUnknownInstance(rd::SerializationCtx& ctx, rd::Buffer & buffer, rd::RdId const& unknownId, int32_t size)
{
    int32_t objectStartPosition = buffer.get_position();
    auto _id = rd::RdId::read(buffer);
    auto baseField_ = buffer.read_integral<int32_t>();
    auto unknownBytes = rd::Buffer::ByteArray(objectStartPosition + size - buffer.get_position());
    buffer.read_byte_array_raw(unknownBytes);
    BaseClass_Unknown res{std::move(baseField_), unknownId, unknownBytes};
    withId(res, _id);
    return rd::Wrapper<BaseClass_Unknown>(std::move(res));
}
// writer
// virtual init
void BaseClass::init(rd::Lifetime lifetime) const
{
    rd::RdBindableBase::init(lifetime);
}
// identify
void BaseClass::identify(const rd::Identities &identities, rd::RdId const &id) const
{
    rd::RdBindableBase::identify(identities, id);
}
// getters
int32_t const & BaseClass::get_baseField() const
{
    return baseField_;
}
// intern
// equals trait
// equality operators
bool operator==(const BaseClass &lhs, const BaseClass &rhs) {
    return &lhs == &rhs;
}
bool operator!=(const BaseClass &lhs, const BaseClass &rhs){
    return !(lhs == rhs);
}
// hash code trait
// type name trait
std::string BaseClass::type_name() const
{
    return "BaseClass";
}
// static type name trait
std::string BaseClass::static_type_name()
{
    return "BaseClass";
}
// polymorphic to string
std::string BaseClass::toString() const
{
    std::string res = "BaseClass\n";
    res += "\tbaseField = ";
    res += rd::to_string(baseField_);
    res += '\n';
    return res;
}
// external to string
std::string to_string(const BaseClass & value)
{
    return value.toString();
}
}

#ifdef _MSC_VER
#pragma warning( pop )
#endif

