//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "DerivedBaseStruct_Unknown.Generated.h"



#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace org.example {
// companion
// constants
// initializer
void DerivedBaseStruct_Unknown::initialize()
{
}
// primary ctor
DerivedBaseStruct_Unknown::DerivedBaseStruct_Unknown(bool derivedField_, int32_t baseField_, rd::RdId unknownId_, rd::Buffer::ByteArray unknownBytes_) :
DerivedBaseStruct(std::move(derivedField_),std::move(baseField_)), rd::IUnknownInstance(std::move(unknownId_))

{
    initialize();
}
// secondary constructor
// default ctors and dtors
// reader
DerivedBaseStruct_Unknown DerivedBaseStruct_Unknown::read(rd::SerializationCtx& ctx, rd::Buffer & buffer)
{
    throw std::logic_error("Unknown instances should not be read via serializer");
}
// writer
void DerivedBaseStruct_Unknown::write(rd::SerializationCtx& ctx, rd::Buffer& buffer) const
{
    buffer.write_bool(derivedField_);
    buffer.write_integral(baseField_);
    buffer.write_byte_array_raw(unknownBytes_);
}
// virtual init
// identify
// getters
// intern
// equals trait
bool DerivedBaseStruct_Unknown::equals(rd::ISerializable const& object) const
{
    auto const &other = dynamic_cast<DerivedBaseStruct_Unknown const&>(object);
    if (this == &other) return true;
    if (this->derivedField_ != other.derivedField_) return false;
    if (this->baseField_ != other.baseField_) return false;
    
    return true;
}
// equality operators
bool operator==(const DerivedBaseStruct_Unknown &lhs, const DerivedBaseStruct_Unknown &rhs) {
    if (lhs.type_name() != rhs.type_name()) return false;
    return lhs.equals(rhs);
}
bool operator!=(const DerivedBaseStruct_Unknown &lhs, const DerivedBaseStruct_Unknown &rhs){
    return !(lhs == rhs);
}
// hash code trait
size_t DerivedBaseStruct_Unknown::hashCode() const noexcept
{
    size_t __r = 0;
    __r = __r * 31 + (rd::hash<bool>()(get_derivedField()));
    __r = __r * 31 + (rd::hash<int32_t>()(get_baseField()));
    return __r;
}
// type name trait
std::string DerivedBaseStruct_Unknown::type_name() const
{
    return "DerivedBaseStruct_Unknown";
}
// static type name trait
std::string DerivedBaseStruct_Unknown::static_type_name()
{
    return "DerivedBaseStruct_Unknown";
}
// polymorphic to string
std::string DerivedBaseStruct_Unknown::toString() const
{
    std::string res = "DerivedBaseStruct_Unknown\n";
    res += "\tderivedField = ";
    res += rd::to_string(derivedField_);
    res += '\n';
    res += "\tbaseField = ";
    res += rd::to_string(baseField_);
    res += '\n';
    return res;
}
// external to string
std::string to_string(const DerivedBaseStruct_Unknown & value)
{
    return value.toString();
}
}

#ifdef _MSC_VER
#pragma warning( pop )
#endif

