//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.08.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "EnumSetTest.Generated.h"

namespace org.example {
std::string to_string(const EnumSetTest & value)
{
    switch(value) {
    case EnumSetTest::a: return "a";
    case EnumSetTest::b: return "b";
    case EnumSetTest::c: return "c";
    default: return std::to_string(static_cast<int32_t>(value));
    }
}
}
