//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.09.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Foo.Generated.h"


#include "Foo_Unknown.Generated.h"

#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace org.example {
// companion
// constants
// initializer
void Foo::initialize()
{
    sdf_.optimize_nested = true;
}
// primary ctor
Foo::Foo(int32_t x_, rd::RdMap<int32_t, int32_t, rd::Polymorphic<int32_t>, rd::Polymorphic<int32_t>> sdf_) :
rd::IPolymorphicSerializable(), rd::RdBindableBase()
,x_(std::move(x_)), sdf_(std::move(sdf_))
{
    initialize();
}
// secondary constructor
// default ctors and dtors
// reader
rd::Wrapper<Foo> Foo::readUnknownInstance(rd::SerializationCtx& ctx, rd::Buffer & buffer, rd::RdId const& unknownId, int32_t size)
{
    int32_t objectStartPosition = buffer.get_position();
    auto _id = rd::RdId::read(buffer);
    auto x_ = buffer.read_integral<int32_t>();
    auto sdf_ = rd::RdMap<int32_t, int32_t, rd::Polymorphic<int32_t>, rd::Polymorphic<int32_t>>::read(ctx, buffer);
    auto unknownBytes = rd::Buffer::ByteArray(objectStartPosition + size - buffer.get_position());
    buffer.read_byte_array_raw(unknownBytes);
    Foo_Unknown res{std::move(x_), std::move(sdf_), unknownId, unknownBytes};
    withId(res, _id);
    return rd::Wrapper<Foo_Unknown>(std::move(res));
}
// writer
// virtual init
void Foo::init(rd::Lifetime lifetime) const
{
    rd::RdBindableBase::init(lifetime);
    bindPolymorphic(sdf_, lifetime, this, "sdf");
}
// identify
void Foo::identify(const rd::Identities &identities, rd::RdId const &id) const
{
    rd::RdBindableBase::identify(identities, id);
    identifyPolymorphic(sdf_, identities, id.mix(".sdf"));
}
// getters
int32_t const & Foo::get_x() const
{
    return x_;
}
rd::IViewableMap<int32_t, int32_t> const & Foo::get_sdf() const
{
    return sdf_;
}
// intern
// equals trait
// equality operators
bool operator==(const Foo &lhs, const Foo &rhs) {
    return &lhs == &rhs;
}
bool operator!=(const Foo &lhs, const Foo &rhs){
    return !(lhs == rhs);
}
// hash code trait
// type name trait
std::string Foo::type_name() const
{
    return "Foo";
}
// static type name trait
std::string Foo::static_type_name()
{
    return "Foo";
}
// polymorphic to string
std::string Foo::toString() const
{
    std::string res = "Foo\n";
    res += "\tx = ";
    res += rd::to_string(x_);
    res += '\n';
    res += "\tsdf = ";
    res += rd::to_string(sdf_);
    res += '\n';
    return res;
}
// external to string
std::string to_string(const Foo & value)
{
    return value.toString();
}
}

#ifdef _MSC_VER
#pragma warning( pop )
#endif

