//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.11.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Interface.Generated.h"



#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace org.example {
// companion
// constants
// initializer
void Interface::initialize()
{
}
// primary ctor
// secondary constructor
// default ctors and dtors
Interface::Interface()
{
    initialize();
}
// reader
// writer
// virtual init
// identify
// getters
// intern
// equals trait
bool Interface::equals(rd::ISerializable const& object) const
{
    auto const &other = dynamic_cast<Interface const&>(object);
    return this == &other;
}
// equality operators
bool operator==(const Interface &lhs, const Interface &rhs) {
    return &lhs == &rhs;
}
bool operator!=(const Interface &lhs, const Interface &rhs){
    return !(lhs == rhs);
}
// hash code trait
// type name trait
std::string Interface::type_name() const
{
    return "Interface";
}
// static type name trait
std::string Interface::static_type_name()
{
    return "Interface";
}
// polymorphic to string
std::string Interface::toString() const
{
    std::string res = "Interface\n";
    return res;
}
// external to string
std::string to_string(const Interface & value)
{
    return value.toString();
}
}

#ifdef _MSC_VER
#pragma warning( pop )
#endif

