//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.11.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Interface2.Generated.h"



#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace org.example {
// companion
// constants
// initializer
void Interface2::initialize()
{
}
// primary ctor
// secondary constructor
// default ctors and dtors
Interface2::Interface2()
{
    initialize();
}
// reader
// writer
// virtual init
// identify
// getters
// intern
// equals trait
bool Interface2::equals(rd::ISerializable const& object) const
{
    auto const &other = dynamic_cast<Interface2 const&>(object);
    return this == &other;
}
// equality operators
bool operator==(const Interface2 &lhs, const Interface2 &rhs) {
    return &lhs == &rhs;
}
bool operator!=(const Interface2 &lhs, const Interface2 &rhs){
    return !(lhs == rhs);
}
// hash code trait
// type name trait
std::string Interface2::type_name() const
{
    return "Interface2";
}
// static type name trait
std::string Interface2::static_type_name()
{
    return "Interface2";
}
// polymorphic to string
std::string Interface2::toString() const
{
    std::string res = "Interface2\n";
    return res;
}
// external to string
std::string to_string(const Interface2 & value)
{
    return value.toString();
}
}

#ifdef _MSC_VER
#pragma warning( pop )
#endif

