//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace org.example
{
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:21</p>
  /// </summary>
  public class ExampleModelNova : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public void Push(int value) => _Push.Fire(value);
    [NotNull] public IReadonlyProperty<int> Version => _Version;
    [NotNull] public IViewableMap<int, Document> Documents => _Documents;
    [NotNull] public IViewableMap<ScalarExample, TextControl> Editors => _Editors;
    [NotNull] public IViewableProperty<UseStructTest> NonNullableStruct => _NonNullableStruct;
    [NotNull] public IViewableProperty<UseStructTest?> NullableStruct => _NullableStruct;
    
    //private fields
    [NotNull] private readonly RdSignal<int> _Push;
    [NotNull] private readonly RdProperty<int> _Version;
    [NotNull] private readonly RdMap<int, Document> _Documents;
    [NotNull] private readonly RdMap<ScalarExample, TextControl> _Editors;
    [NotNull] private readonly RdProperty<UseStructTest> _NonNullableStruct;
    [NotNull] private readonly RdProperty<UseStructTest?> _NullableStruct;
    
    //primary constructor
    private ExampleModelNova(
      [NotNull] RdSignal<int> push,
      [NotNull] RdProperty<int> version,
      [NotNull] RdMap<int, Document> documents,
      [NotNull] RdMap<ScalarExample, TextControl> editors,
      [NotNull] RdProperty<UseStructTest> nonNullableStruct,
      [NotNull] RdProperty<UseStructTest?> nullableStruct
    )
    {
      if (push == null) throw new ArgumentNullException("push");
      if (version == null) throw new ArgumentNullException("version");
      if (documents == null) throw new ArgumentNullException("documents");
      if (editors == null) throw new ArgumentNullException("editors");
      if (nonNullableStruct == null) throw new ArgumentNullException("nonNullableStruct");
      if (nullableStruct == null) throw new ArgumentNullException("nullableStruct");
      
      _Push = push;
      _Version = version;
      _Documents = documents;
      _Editors = editors;
      _NonNullableStruct = nonNullableStruct;
      _NullableStruct = nullableStruct;
      _Version.OptimizeNested = true;
      _NonNullableStruct.OptimizeNested = true;
      _NullableStruct.OptimizeNested = true;
      _NullableStruct.ValueCanBeNull = true;
      BindableChildren.Add(new KeyValuePair<string, object>("push", _Push));
      BindableChildren.Add(new KeyValuePair<string, object>("version", _Version));
      BindableChildren.Add(new KeyValuePair<string, object>("documents", _Documents));
      BindableChildren.Add(new KeyValuePair<string, object>("editors", _Editors));
      BindableChildren.Add(new KeyValuePair<string, object>("nonNullableStruct", _NonNullableStruct));
      BindableChildren.Add(new KeyValuePair<string, object>("nullableStruct", _NullableStruct));
    }
    //secondary constructor
    private ExampleModelNova (
    ) : this (
      new RdSignal<int>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt),
      new RdProperty<int>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt),
      new RdMap<int, Document>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, Document.Read, Document.Write),
      new RdMap<ScalarExample, TextControl>(ScalarExample.Read, ScalarExample.Write, TextControl.Read, TextControl.Write),
      new RdProperty<UseStructTest>(UseStructTest.Read, UseStructTest.Write),
      new RdProperty<UseStructTest?>(ReadUseStructTestNullable, WriteUseStructTestNullable)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<UseStructTest?> ReadUseStructTestNullable = UseStructTest.Read.NullableStruct();
    
    public static  CtxWriteDelegate<UseStructTest?> WriteUseStructTestNullable = UseStructTest.Write.NullableStruct();
    
    protected override long SerializationHash => -4242378315094463055L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      serializers.Register(Baz.Read, Baz.Write);
      serializers.Register(OpenClass.Read, OpenClass.Write);
      serializers.Register(OpenStruct.Read, OpenStruct.Write);
      serializers.Register(DerivedClass.Read, DerivedClass.Write);
      serializers.Register(DerivedStruct.Read, DerivedStruct.Write);
      serializers.Register(DerivedOpenClass.Read, DerivedOpenClass.Write);
      serializers.Register(DerivedOpenStruct.Read, DerivedOpenStruct.Write);
      serializers.Register(DerivedStructWith2Interfaces.Read, DerivedStructWith2Interfaces.Write);
      serializers.Register(Foo_Unknown.Read, Foo_Unknown.Write);
      serializers.Register(ScalarPrimer_Unknown.Read, ScalarPrimer_Unknown.Write);
      serializers.Register(A_Unknown.Read, A_Unknown.Write);
      serializers.Register(BaseClass_Unknown.Read, BaseClass_Unknown.Write);
      serializers.Register(BaseStruct_Unknown.Read, BaseStruct_Unknown.Write);
      serializers.Register(OpenClass_Unknown.Read, OpenClass_Unknown.Write);
      serializers.Register(OpenStruct_Unknown.Read, OpenStruct_Unknown.Write);
      serializers.Register(DerivedOpenClass_Unknown.Read, DerivedOpenClass_Unknown.Write);
      serializers.Register(DerivedOpenStruct_Unknown.Read, DerivedOpenStruct_Unknown.Write);
      serializers.Register(DerivedBaseClass_Unknown.Read, DerivedBaseClass_Unknown.Write);
      serializers.Register(DerivedBaseStruct_Unknown.Read, DerivedBaseStruct_Unknown.Write);
      serializers.Register(BaseClassWithInterface_Unknown.Read, BaseClassWithInterface_Unknown.Write);
      serializers.Register(BaseStructWithInterface_Unknown.Read, BaseStructWithInterface_Unknown.Write);
      serializers.Register(DerivedClassWith2Interfaces_Unknown.Read, DerivedClassWith2Interfaces_Unknown.Write);
      
      serializers.RegisterToplevelOnce(typeof(ExampleRootNova), ExampleRootNova.RegisterDeclaredTypesSerializers);
    }
    
    public ExampleModelNova(Lifetime lifetime, IProtocol protocol) : this()
    {
      Identify(protocol.Identities, protocol.Identities.Mix(RdId.Root, "ExampleModelNova"));
      this.BindTopLevel(lifetime, protocol, "ExampleModelNova");
    }
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("ExampleModelNova (");
      using (printer.IndentCookie()) {
        printer.Print("push = "); _Push.PrintEx(printer); printer.Println();
        printer.Print("version = "); _Version.PrintEx(printer); printer.Println();
        printer.Print("documents = "); _Documents.PrintEx(printer); printer.Println();
        printer.Print("editors = "); _Editors.PrintEx(printer); printer.Println();
        printer.Print("nonNullableStruct = "); _NonNullableStruct.PrintEx(printer); printer.Println();
        printer.Print("nullableStruct = "); _NullableStruct.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:44</p>
  /// </summary>
  public abstract class A : Foo
  {
    //fields
    //public fields
    [NotNull] public IViewableProperty<string> Y => _Y;
    [NotNull] public IViewableProperty<org.example.Z> Z => _Z;
    
    //private fields
    [NotNull] protected readonly RdProperty<string> _Y;
    [NotNull] protected readonly RdProperty<org.example.Z> _Z;
    
    //primary constructor
    protected A(
      [NotNull] RdProperty<string> y,
      [NotNull] RdProperty<org.example.Z> z,
      int x,
      [NotNull] RdMap<int, int> sdf
    ) : base (
      x,
      sdf
     ) 
    {
      if (y == null) throw new ArgumentNullException("y");
      if (z == null) throw new ArgumentNullException("z");
      
      _Y = y;
      _Z = z;
      _Y.OptimizeNested = true;
      _Z.OptimizeNested = true;
      BindableChildren.Add(new KeyValuePair<string, object>("y", _Y));
      BindableChildren.Add(new KeyValuePair<string, object>("z", _Z));
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<A> Read = Polymorphic<A>.ReadAbstract(A_Unknown.Read);
    
    public static new CtxWriteDelegate<A> Write = Polymorphic<A>.Write;
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    //toString
  }
  
  
  public sealed class A_Unknown : A
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    private A_Unknown(
      [NotNull] RdProperty<string> y,
      [NotNull] RdProperty<org.example.Z> z,
      int x,
      [NotNull] RdMap<int, int> sdf
    ) : base (
      y,
      z,
      x,
      sdf
     ) 
    {
    }
    //secondary constructor
    public A_Unknown (
      int x
    ) : this (
      new RdProperty<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString),
      new RdProperty<org.example.Z>(ReadZ, WriteZ),
      x,
      new RdMap<int, int>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt)
    ) {}
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<A_Unknown> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var y = RdProperty<string>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString);
      var z = RdProperty<org.example.Z>.Read(ctx, reader, ReadZ, WriteZ);
      var x = reader.ReadInt();
      var sdf = RdMap<int, int>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt);
      var _result = new A_Unknown(y, z, x, sdf).WithId(_id);
      return _result;
    };
    public static CtxReadDelegate<org.example.Z> ReadZ = new CtxReadDelegate<org.example.Z>(JetBrains.Rd.Impl.Serializers.ReadEnum<org.example.Z>);
    
    public static new CtxWriteDelegate<A_Unknown> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      RdProperty<string>.Write(ctx, writer, value._Y);
      RdProperty<org.example.Z>.Write(ctx, writer, value._Z);
      writer.Write(value.X);
      RdMap<int, int>.Write(ctx, writer, value._Sdf);
    };
    public static  CtxWriteDelegate<org.example.Z> WriteZ = new CtxWriteDelegate<org.example.Z>(JetBrains.Rd.Impl.Serializers.WriteEnum<org.example.Z>);
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("A_Unknown (");
      using (printer.IndentCookie()) {
        printer.Print("y = "); _Y.PrintEx(printer); printer.Println();
        printer.Print("z = "); _Z.PrintEx(printer); printer.Println();
        printer.Print("x = "); X.PrintEx(printer); printer.Println();
        printer.Print("sdf = "); _Sdf.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:93</p>
  /// </summary>
  public abstract class BaseClass : RdBindableBase
  {
    //fields
    //public fields
    public int BaseField {get; private set;}
    
    //private fields
    //primary constructor
    protected BaseClass(
      int baseField
    )
    {
      BaseField = baseField;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<BaseClass> Read = Polymorphic<BaseClass>.ReadAbstract(BaseClass_Unknown.Read);
    
    public static CtxWriteDelegate<BaseClass> Write = Polymorphic<BaseClass>.Write;
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    //toString
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:133</p>
  /// </summary>
  public abstract class BaseClassWithInterface : RdBindableBase, Interface
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<BaseClassWithInterface> Read = Polymorphic<BaseClassWithInterface>.ReadAbstract(BaseClassWithInterface_Unknown.Read);
    
    public static CtxWriteDelegate<BaseClassWithInterface> Write = Polymorphic<BaseClassWithInterface>.Write;
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    //toString
  }
  
  
  public sealed class BaseClassWithInterface_Unknown : BaseClassWithInterface
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<BaseClassWithInterface_Unknown> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var _result = new BaseClassWithInterface_Unknown().WithId(_id);
      return _result;
    };
    
    public static new CtxWriteDelegate<BaseClassWithInterface_Unknown> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("BaseClassWithInterface_Unknown (");
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  public sealed class BaseClass_Unknown : BaseClass
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    public BaseClass_Unknown(
      int baseField
    ) : base (
      baseField
     ) 
    {
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<BaseClass_Unknown> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var baseField = reader.ReadInt();
      var _result = new BaseClass_Unknown(baseField).WithId(_id);
      return _result;
    };
    
    public static new CtxWriteDelegate<BaseClass_Unknown> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      writer.Write(value.BaseField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("BaseClass_Unknown (");
      using (printer.IndentCookie()) {
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:97</p>
  /// </summary>
  public abstract class BaseStruct{
    //fields
    //public fields
    public int BaseField {get; private set;}
    
    //private fields
    //primary constructor
    protected BaseStruct(
      int baseField
    )
    {
      BaseField = baseField;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<BaseStruct> Read = Polymorphic<BaseStruct>.ReadAbstract(BaseStruct_Unknown.Read);
    
    public static CtxWriteDelegate<BaseStruct> Write = Polymorphic<BaseStruct>.Write;
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    //toString
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:136</p>
  /// </summary>
  public abstract class BaseStructWithInterface : Interface
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<BaseStructWithInterface> Read = Polymorphic<BaseStructWithInterface>.ReadAbstract(BaseStructWithInterface_Unknown.Read);
    
    public static CtxWriteDelegate<BaseStructWithInterface> Write = Polymorphic<BaseStructWithInterface>.Write;
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    //toString
  }
  
  
  public sealed class BaseStructWithInterface_Unknown : BaseStructWithInterface
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<BaseStructWithInterface_Unknown> Read = (ctx, reader) => 
    {
      var _result = new BaseStructWithInterface_Unknown();
      return _result;
    };
    
    public static new CtxWriteDelegate<BaseStructWithInterface_Unknown> Write = (ctx, writer, value) => 
    {
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((BaseStructWithInterface_Unknown) obj);
    }
    public bool Equals(BaseStructWithInterface_Unknown other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return true;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("BaseStructWithInterface_Unknown (");
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  public sealed class BaseStruct_Unknown : BaseStruct
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    public BaseStruct_Unknown(
      int baseField
    ) : base (
      baseField
     ) 
    {
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<BaseStruct_Unknown> Read = (ctx, reader) => 
    {
      var baseField = reader.ReadInt();
      var _result = new BaseStruct_Unknown(baseField);
      return _result;
    };
    
    public static new CtxWriteDelegate<BaseStruct_Unknown> Write = (ctx, writer, value) => 
    {
      writer.Write(value.BaseField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((BaseStruct_Unknown) obj);
    }
    public bool Equals(BaseStruct_Unknown other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return BaseField == other.BaseField;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + BaseField.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("BaseStruct_Unknown (");
      using (printer.IndentCookie()) {
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:52</p>
  /// </summary>
  public sealed class Baz : A
  {
    //fields
    //public fields
    [NotNull] public List<org.example.Foo> Foo {get; private set;}
    [NotNull] public List<A> Bar {get; private set;}
    [NotNull] public string Nls_field {get; private set;}
    [CanBeNull] public string Nls_nullable_field {get; private set;}
    [NotNull] public List<string> String_list_field {get; private set;}
    [NotNull] public List<string> Nls_list_field {get; private set;}
    [NotNull] public IViewableProperty<org.example.Foo> Foo1 => _Foo1;
    [NotNull] public IViewableProperty<A> Bar1 => _Bar1;
    [NotNull] public IViewableMap<int, ScalarPrimer> MapScalar => _MapScalar;
    [NotNull] public IViewableMap<int, FooBar> MapBindable => _MapBindable;
    [NotNull] public IViewableProperty<string> Property_with_default_nls => _Property_with_default_nls;
    [NotNull] public IViewableProperty<string> Property_with_several_attrs => _Property_with_several_attrs;
    [NotNull] public IViewableProperty<string> Nls_prop => _Nls_prop;
    [NotNull] public IViewableProperty<string> Nullable_nls_prop => _Nullable_nls_prop;
    [NotNull] public string Non_nls_open_field {get; private set;}
    [NotNull] public IViewableProperty<TimeSpan> Duration_prop => _Duration_prop;
    
    //private fields
    [NotNull] private readonly RdProperty<org.example.Foo> _Foo1;
    [NotNull] private readonly RdProperty<A> _Bar1;
    [NotNull] private readonly RdMap<int, ScalarPrimer> _MapScalar;
    [NotNull] private readonly RdMap<int, FooBar> _MapBindable;
    [NotNull] private readonly RdProperty<string> _Property_with_default_nls;
    [NotNull] private readonly RdProperty<string> _Property_with_several_attrs;
    [NotNull] private readonly RdProperty<string> _Nls_prop;
    [NotNull] private readonly RdProperty<string> _Nullable_nls_prop;
    [NotNull] private readonly RdProperty<TimeSpan> _Duration_prop;
    
    //primary constructor
    private Baz(
      [NotNull] List<org.example.Foo> foo,
      [NotNull] List<A> bar,
      [NotNull] string nls_field,
      [CanBeNull] string nls_nullable_field,
      [NotNull] List<string> string_list_field,
      [NotNull] List<string> nls_list_field,
      [NotNull] RdProperty<org.example.Foo> foo1,
      [NotNull] RdProperty<A> bar1,
      [NotNull] RdMap<int, ScalarPrimer> mapScalar,
      [NotNull] RdMap<int, FooBar> mapBindable,
      [NotNull] RdProperty<string> property_with_default_nls,
      [NotNull] RdProperty<string> property_with_several_attrs,
      [NotNull] RdProperty<string> nls_prop,
      [NotNull] RdProperty<string> nullable_nls_prop,
      [NotNull] string non_nls_open_field,
      [NotNull] RdProperty<TimeSpan> duration_prop,
      [NotNull] RdProperty<string> y,
      [NotNull] RdProperty<org.example.Z> z,
      int x,
      [NotNull] RdMap<int, int> sdf
    ) : base (
      y,
      z,
      x,
      sdf
     ) 
    {
      if (foo == null) throw new ArgumentNullException("foo");
      if (bar == null) throw new ArgumentNullException("bar");
      if (nls_field == null) throw new ArgumentNullException("nls_field");
      if (string_list_field == null) throw new ArgumentNullException("string_list_field");
      if (nls_list_field == null) throw new ArgumentNullException("nls_list_field");
      if (foo1 == null) throw new ArgumentNullException("foo1");
      if (bar1 == null) throw new ArgumentNullException("bar1");
      if (mapScalar == null) throw new ArgumentNullException("mapScalar");
      if (mapBindable == null) throw new ArgumentNullException("mapBindable");
      if (property_with_default_nls == null) throw new ArgumentNullException("property_with_default_nls");
      if (property_with_several_attrs == null) throw new ArgumentNullException("property_with_several_attrs");
      if (nls_prop == null) throw new ArgumentNullException("nls_prop");
      if (nullable_nls_prop == null) throw new ArgumentNullException("nullable_nls_prop");
      if (non_nls_open_field == null) throw new ArgumentNullException("non_nls_open_field");
      if (duration_prop == null) throw new ArgumentNullException("duration_prop");
      
      Foo = foo;
      Bar = bar;
      Nls_field = nls_field;
      Nls_nullable_field = nls_nullable_field;
      String_list_field = string_list_field;
      Nls_list_field = nls_list_field;
      _Foo1 = foo1;
      _Bar1 = bar1;
      _MapScalar = mapScalar;
      _MapBindable = mapBindable;
      _Property_with_default_nls = property_with_default_nls;
      _Property_with_several_attrs = property_with_several_attrs;
      _Nls_prop = nls_prop;
      _Nullable_nls_prop = nullable_nls_prop;
      Non_nls_open_field = non_nls_open_field;
      _Duration_prop = duration_prop;
      _MapScalar.OptimizeNested = true;
      _Property_with_default_nls.OptimizeNested = true;
      _Property_with_several_attrs.OptimizeNested = true;
      _Nls_prop.OptimizeNested = true;
      _Nullable_nls_prop.OptimizeNested = true;
      _Duration_prop.OptimizeNested = true;
      _MapScalar.Async = true;
      _Foo1.ValueCanBeNull = true;
      _Bar1.ValueCanBeNull = true;
      _Nullable_nls_prop.ValueCanBeNull = true;
      BindableChildren.Add(new KeyValuePair<string, object>("foo", Foo));
      BindableChildren.Add(new KeyValuePair<string, object>("bar", Bar));
      BindableChildren.Add(new KeyValuePair<string, object>("foo1", _Foo1));
      BindableChildren.Add(new KeyValuePair<string, object>("bar1", _Bar1));
      BindableChildren.Add(new KeyValuePair<string, object>("mapScalar", _MapScalar));
      BindableChildren.Add(new KeyValuePair<string, object>("mapBindable", _MapBindable));
      BindableChildren.Add(new KeyValuePair<string, object>("property_with_default_nls", _Property_with_default_nls));
      BindableChildren.Add(new KeyValuePair<string, object>("property_with_several_attrs", _Property_with_several_attrs));
      BindableChildren.Add(new KeyValuePair<string, object>("nls_prop", _Nls_prop));
      BindableChildren.Add(new KeyValuePair<string, object>("nullable_nls_prop", _Nullable_nls_prop));
      BindableChildren.Add(new KeyValuePair<string, object>("duration_prop", _Duration_prop));
    }
    //secondary constructor
    public Baz (
      [NotNull] List<org.example.Foo> foo,
      [NotNull] List<A> bar,
      [NotNull] string nls_field,
      [CanBeNull] string nls_nullable_field,
      [NotNull] List<string> string_list_field,
      [NotNull] List<string> nls_list_field,
      [NotNull] string non_nls_open_field,
      int x
    ) : this (
      foo,
      bar,
      nls_field,
      nls_nullable_field,
      string_list_field,
      nls_list_field,
      new RdProperty<org.example.Foo>(ReadFooNullable, WriteFooNullable),
      new RdProperty<A>(ReadANullable, WriteANullable),
      new RdMap<int, ScalarPrimer>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, ScalarPrimer.Read, ScalarPrimer.Write),
      new RdMap<int, FooBar>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, FooBar.Read, FooBar.Write),
      new RdProperty<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString, const_for_default_nls),
      new RdProperty<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString),
      new RdProperty<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString),
      new RdProperty<string>(ReadStringNullable, WriteStringNullable),
      non_nls_open_field,
      new RdProperty<TimeSpan>(JetBrains.Rd.Impl.Serializers.ReadTimeSpan, JetBrains.Rd.Impl.Serializers.WriteTimeSpan),
      new RdProperty<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString),
      new RdProperty<org.example.Z>(ReadZ, WriteZ),
      x,
      new RdMap<int, int>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt)
    ) {}
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<Baz> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var y = RdProperty<string>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString);
      var z = RdProperty<org.example.Z>.Read(ctx, reader, ReadZ, WriteZ);
      var x = reader.ReadInt();
      var sdf = RdMap<int, int>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt);
      var foo = ReadFooList(ctx, reader);
      var bar = ReadANullableList(ctx, reader);
      var nls_field = reader.ReadString();
      var nls_nullable_field = ReadStringNullable(ctx, reader);
      var string_list_field = ReadStringList(ctx, reader);
      var nls_list_field = ReadStringList(ctx, reader);
      var foo1 = RdProperty<org.example.Foo>.Read(ctx, reader, ReadFooNullable, WriteFooNullable);
      var bar1 = RdProperty<A>.Read(ctx, reader, ReadANullable, WriteANullable);
      var mapScalar = RdMap<int, ScalarPrimer>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, ScalarPrimer.Read, ScalarPrimer.Write);
      var mapBindable = RdMap<int, FooBar>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, FooBar.Read, FooBar.Write);
      var property_with_default_nls = RdProperty<string>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString);
      var property_with_several_attrs = RdProperty<string>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString);
      var nls_prop = RdProperty<string>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString);
      var nullable_nls_prop = RdProperty<string>.Read(ctx, reader, ReadStringNullable, WriteStringNullable);
      var non_nls_open_field = reader.ReadString();
      var duration_prop = RdProperty<TimeSpan>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadTimeSpan, JetBrains.Rd.Impl.Serializers.WriteTimeSpan);
      var _result = new Baz(foo, bar, nls_field, nls_nullable_field, string_list_field, nls_list_field, foo1, bar1, mapScalar, mapBindable, property_with_default_nls, property_with_several_attrs, nls_prop, nullable_nls_prop, non_nls_open_field, duration_prop, y, z, x, sdf).WithId(_id);
      return _result;
    };
    public static CtxReadDelegate<List<org.example.Foo>> ReadFooList = org.example.Foo.Read.List();
    public static CtxReadDelegate<List<A>> ReadANullableList = A.Read.NullableClass().List();
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    public static CtxReadDelegate<org.example.Foo> ReadFooNullable = org.example.Foo.Read.NullableClass();
    public static CtxReadDelegate<A> ReadANullable = A.Read.NullableClass();
    public static CtxReadDelegate<org.example.Z> ReadZ = new CtxReadDelegate<org.example.Z>(JetBrains.Rd.Impl.Serializers.ReadEnum<org.example.Z>);
    
    public static new CtxWriteDelegate<Baz> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      RdProperty<string>.Write(ctx, writer, value._Y);
      RdProperty<org.example.Z>.Write(ctx, writer, value._Z);
      writer.Write(value.X);
      RdMap<int, int>.Write(ctx, writer, value._Sdf);
      WriteFooList(ctx, writer, value.Foo);
      WriteANullableList(ctx, writer, value.Bar);
      writer.Write(value.Nls_field);
      WriteStringNullable(ctx, writer, value.Nls_nullable_field);
      WriteStringList(ctx, writer, value.String_list_field);
      WriteStringList(ctx, writer, value.Nls_list_field);
      RdProperty<org.example.Foo>.Write(ctx, writer, value._Foo1);
      RdProperty<A>.Write(ctx, writer, value._Bar1);
      RdMap<int, ScalarPrimer>.Write(ctx, writer, value._MapScalar);
      RdMap<int, FooBar>.Write(ctx, writer, value._MapBindable);
      RdProperty<string>.Write(ctx, writer, value._Property_with_default_nls);
      RdProperty<string>.Write(ctx, writer, value._Property_with_several_attrs);
      RdProperty<string>.Write(ctx, writer, value._Nls_prop);
      RdProperty<string>.Write(ctx, writer, value._Nullable_nls_prop);
      writer.Write(value.Non_nls_open_field);
      RdProperty<TimeSpan>.Write(ctx, writer, value._Duration_prop);
    };
    public static  CtxWriteDelegate<List<org.example.Foo>> WriteFooList = org.example.Foo.Write.List();
    public static  CtxWriteDelegate<List<A>> WriteANullableList = A.Write.NullableClass().List();
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    public static  CtxWriteDelegate<org.example.Foo> WriteFooNullable = org.example.Foo.Write.NullableClass();
    public static  CtxWriteDelegate<A> WriteANullable = A.Write.NullableClass();
    public static  CtxWriteDelegate<org.example.Z> WriteZ = new CtxWriteDelegate<org.example.Z>(JetBrains.Rd.Impl.Serializers.WriteEnum<org.example.Z>);
    
    //constants
    public const string const_nls = const_nls_value;
    public const string const_for_default_nls = 291;
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("Baz (");
      using (printer.IndentCookie()) {
        printer.Print("foo = "); Foo.PrintEx(printer); printer.Println();
        printer.Print("bar = "); Bar.PrintEx(printer); printer.Println();
        printer.Print("nls_field = "); Nls_field.PrintEx(printer); printer.Println();
        printer.Print("nls_nullable_field = "); Nls_nullable_field.PrintEx(printer); printer.Println();
        printer.Print("string_list_field = "); String_list_field.PrintEx(printer); printer.Println();
        printer.Print("nls_list_field = "); Nls_list_field.PrintEx(printer); printer.Println();
        printer.Print("foo1 = "); _Foo1.PrintEx(printer); printer.Println();
        printer.Print("bar1 = "); _Bar1.PrintEx(printer); printer.Println();
        printer.Print("mapScalar = "); _MapScalar.PrintEx(printer); printer.Println();
        printer.Print("mapBindable = "); _MapBindable.PrintEx(printer); printer.Println();
        printer.Print("property_with_default_nls = "); _Property_with_default_nls.PrintEx(printer); printer.Println();
        printer.Print("property_with_several_attrs = "); _Property_with_several_attrs.PrintEx(printer); printer.Println();
        printer.Print("nls_prop = "); _Nls_prop.PrintEx(printer); printer.Println();
        printer.Print("nullable_nls_prop = "); _Nullable_nls_prop.PrintEx(printer); printer.Println();
        printer.Print("non_nls_open_field = "); Non_nls_open_field.PrintEx(printer); printer.Println();
        printer.Print("duration_prop = "); _Duration_prop.PrintEx(printer); printer.Println();
        printer.Print("y = "); _Y.PrintEx(printer); printer.Println();
        printer.Print("z = "); _Z.PrintEx(printer); printer.Println();
        printer.Print("x = "); X.PrintEx(printer); printer.Println();
        printer.Print("sdf = "); _Sdf.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:87</p>
  /// </summary>
  public sealed class Class : RdBindableBase
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<Class> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var _result = new Class().WithId(_id);
      return _result;
    };
    
    public static CtxWriteDelegate<Class> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("Class (");
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:167</p>
  /// </summary>
  public sealed class Completion : RdBindableBase
  {
    //fields
    //public fields
    [NotNull] public IViewableMap<int, bool> LookupItems => _LookupItems;
    
    //private fields
    [NotNull] private readonly RdMap<int, bool> _LookupItems;
    
    //primary constructor
    private Completion(
      [NotNull] RdMap<int, bool> lookupItems
    )
    {
      if (lookupItems == null) throw new ArgumentNullException("lookupItems");
      
      _LookupItems = lookupItems;
      _LookupItems.OptimizeNested = true;
      BindableChildren.Add(new KeyValuePair<string, object>("lookupItems", _LookupItems));
    }
    //secondary constructor
    public Completion (
    ) : this (
      new RdMap<int, bool>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<Completion> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var lookupItems = RdMap<int, bool>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool);
      var _result = new Completion(lookupItems).WithId(_id);
      return _result;
    };
    
    public static CtxWriteDelegate<Completion> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      RdMap<int, bool>.Write(ctx, writer, value._LookupItems);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("Completion (");
      using (printer.IndentCookie()) {
        printer.Print("lookupItems = "); _LookupItems.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:125</p>
  /// </summary>
  public abstract class DerivedBaseClass : BaseClass
  {
    //fields
    //public fields
    public bool DerivedField {get; private set;}
    
    //private fields
    //primary constructor
    protected DerivedBaseClass(
      bool derivedField,
      int baseField
    ) : base (
      baseField
     ) 
    {
      DerivedField = derivedField;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<DerivedBaseClass> Read = Polymorphic<DerivedBaseClass>.ReadAbstract(DerivedBaseClass_Unknown.Read);
    
    public static new CtxWriteDelegate<DerivedBaseClass> Write = Polymorphic<DerivedBaseClass>.Write;
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    //toString
  }
  
  
  public sealed class DerivedBaseClass_Unknown : DerivedBaseClass
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    public DerivedBaseClass_Unknown(
      bool derivedField,
      int baseField
    ) : base (
      derivedField,
      baseField
     ) 
    {
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<DerivedBaseClass_Unknown> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var derivedField = reader.ReadBool();
      var baseField = reader.ReadInt();
      var _result = new DerivedBaseClass_Unknown(derivedField, baseField).WithId(_id);
      return _result;
    };
    
    public static new CtxWriteDelegate<DerivedBaseClass_Unknown> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      writer.Write(value.DerivedField);
      writer.Write(value.BaseField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("DerivedBaseClass_Unknown (");
      using (printer.IndentCookie()) {
        printer.Print("derivedField = "); DerivedField.PrintEx(printer); printer.Println();
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:129</p>
  /// </summary>
  public abstract class DerivedBaseStruct : BaseStruct
  {
    //fields
    //public fields
    public bool DerivedField {get; private set;}
    
    //private fields
    //primary constructor
    protected DerivedBaseStruct(
      bool derivedField,
      int baseField
    ) : base (
      baseField
     ) 
    {
      DerivedField = derivedField;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<DerivedBaseStruct> Read = Polymorphic<DerivedBaseStruct>.ReadAbstract(DerivedBaseStruct_Unknown.Read);
    
    public static new CtxWriteDelegate<DerivedBaseStruct> Write = Polymorphic<DerivedBaseStruct>.Write;
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    //toString
  }
  
  
  public sealed class DerivedBaseStruct_Unknown : DerivedBaseStruct
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    public DerivedBaseStruct_Unknown(
      bool derivedField,
      int baseField
    ) : base (
      derivedField,
      baseField
     ) 
    {
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<DerivedBaseStruct_Unknown> Read = (ctx, reader) => 
    {
      var derivedField = reader.ReadBool();
      var baseField = reader.ReadInt();
      var _result = new DerivedBaseStruct_Unknown(derivedField, baseField);
      return _result;
    };
    
    public static new CtxWriteDelegate<DerivedBaseStruct_Unknown> Write = (ctx, writer, value) => 
    {
      writer.Write(value.DerivedField);
      writer.Write(value.BaseField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((DerivedBaseStruct_Unknown) obj);
    }
    public bool Equals(DerivedBaseStruct_Unknown other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return DerivedField == other.DerivedField && BaseField == other.BaseField;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + DerivedField.GetHashCode();
        hash = hash * 31 + BaseField.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("DerivedBaseStruct_Unknown (");
      using (printer.IndentCookie()) {
        printer.Print("derivedField = "); DerivedField.PrintEx(printer); printer.Println();
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:109</p>
  /// </summary>
  public sealed class DerivedClass : BaseClass
  {
    //fields
    //public fields
    public bool DerivedField {get; private set;}
    
    //private fields
    //primary constructor
    public DerivedClass(
      bool derivedField,
      int baseField
    ) : base (
      baseField
     ) 
    {
      DerivedField = derivedField;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<DerivedClass> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var baseField = reader.ReadInt();
      var derivedField = reader.ReadBool();
      var _result = new DerivedClass(derivedField, baseField).WithId(_id);
      return _result;
    };
    
    public static new CtxWriteDelegate<DerivedClass> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      writer.Write(value.BaseField);
      writer.Write(value.DerivedField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("DerivedClass (");
      using (printer.IndentCookie()) {
        printer.Print("derivedField = "); DerivedField.PrintEx(printer); printer.Println();
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:139</p>
  /// </summary>
  public abstract class DerivedClassWith2Interfaces : BaseClass, Interface, Interface2
  {
    //fields
    //public fields
    public bool DerivedField {get; private set;}
    
    //private fields
    //primary constructor
    protected DerivedClassWith2Interfaces(
      bool derivedField,
      int baseField
    ) : base (
      baseField
     ) 
    {
      DerivedField = derivedField;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<DerivedClassWith2Interfaces> Read = Polymorphic<DerivedClassWith2Interfaces>.ReadAbstract(DerivedClassWith2Interfaces_Unknown.Read);
    
    public static new CtxWriteDelegate<DerivedClassWith2Interfaces> Write = Polymorphic<DerivedClassWith2Interfaces>.Write;
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    //toString
  }
  
  
  public sealed class DerivedClassWith2Interfaces_Unknown : DerivedClassWith2Interfaces
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    public DerivedClassWith2Interfaces_Unknown(
      bool derivedField,
      int baseField
    ) : base (
      derivedField,
      baseField
     ) 
    {
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<DerivedClassWith2Interfaces_Unknown> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var derivedField = reader.ReadBool();
      var baseField = reader.ReadInt();
      var _result = new DerivedClassWith2Interfaces_Unknown(derivedField, baseField).WithId(_id);
      return _result;
    };
    
    public static new CtxWriteDelegate<DerivedClassWith2Interfaces_Unknown> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      writer.Write(value.DerivedField);
      writer.Write(value.BaseField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("DerivedClassWith2Interfaces_Unknown (");
      using (printer.IndentCookie()) {
        printer.Print("derivedField = "); DerivedField.PrintEx(printer); printer.Println();
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:117</p>
  /// </summary>
  public class DerivedOpenClass : OpenClass
  {
    //fields
    //public fields
    public bool DerivedField {get; private set;}
    
    //private fields
    //primary constructor
    public DerivedOpenClass(
      bool derivedField,
      int baseField
    ) : base (
      baseField
     ) 
    {
      DerivedField = derivedField;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<DerivedOpenClass> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var baseField = reader.ReadInt();
      var derivedField = reader.ReadBool();
      var _result = new DerivedOpenClass(derivedField, baseField).WithId(_id);
      return _result;
    };
    
    public static new CtxWriteDelegate<DerivedOpenClass> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      writer.Write(value.BaseField);
      writer.Write(value.DerivedField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("DerivedOpenClass (");
      using (printer.IndentCookie()) {
        printer.Print("derivedField = "); DerivedField.PrintEx(printer); printer.Println();
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  public sealed class DerivedOpenClass_Unknown : DerivedOpenClass
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    public DerivedOpenClass_Unknown(
      bool derivedField,
      int baseField
    ) : base (
      derivedField,
      baseField
     ) 
    {
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<DerivedOpenClass_Unknown> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var derivedField = reader.ReadBool();
      var baseField = reader.ReadInt();
      var _result = new DerivedOpenClass_Unknown(derivedField, baseField).WithId(_id);
      return _result;
    };
    
    public static new CtxWriteDelegate<DerivedOpenClass_Unknown> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      writer.Write(value.DerivedField);
      writer.Write(value.BaseField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("DerivedOpenClass_Unknown (");
      using (printer.IndentCookie()) {
        printer.Print("derivedField = "); DerivedField.PrintEx(printer); printer.Println();
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:121</p>
  /// </summary>
  public class DerivedOpenStruct : OpenStruct
  {
    //fields
    //public fields
    public bool DerivedField {get; private set;}
    
    //private fields
    //primary constructor
    public DerivedOpenStruct(
      bool derivedField,
      int baseField
    ) : base (
      baseField
     ) 
    {
      DerivedField = derivedField;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<DerivedOpenStruct> Read = (ctx, reader) => 
    {
      var baseField = reader.ReadInt();
      var derivedField = reader.ReadBool();
      var _result = new DerivedOpenStruct(derivedField, baseField);
      return _result;
    };
    
    public static new CtxWriteDelegate<DerivedOpenStruct> Write = (ctx, writer, value) => 
    {
      writer.Write(value.BaseField);
      writer.Write(value.DerivedField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((DerivedOpenStruct) obj);
    }
    public bool Equals(DerivedOpenStruct other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return DerivedField == other.DerivedField && BaseField == other.BaseField;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + DerivedField.GetHashCode();
        hash = hash * 31 + BaseField.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("DerivedOpenStruct (");
      using (printer.IndentCookie()) {
        printer.Print("derivedField = "); DerivedField.PrintEx(printer); printer.Println();
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  public sealed class DerivedOpenStruct_Unknown : DerivedOpenStruct
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    public DerivedOpenStruct_Unknown(
      bool derivedField,
      int baseField
    ) : base (
      derivedField,
      baseField
     ) 
    {
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<DerivedOpenStruct_Unknown> Read = (ctx, reader) => 
    {
      var derivedField = reader.ReadBool();
      var baseField = reader.ReadInt();
      var _result = new DerivedOpenStruct_Unknown(derivedField, baseField);
      return _result;
    };
    
    public static new CtxWriteDelegate<DerivedOpenStruct_Unknown> Write = (ctx, writer, value) => 
    {
      writer.Write(value.DerivedField);
      writer.Write(value.BaseField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((DerivedOpenStruct_Unknown) obj);
    }
    public bool Equals(DerivedOpenStruct_Unknown other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return DerivedField == other.DerivedField && BaseField == other.BaseField;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + DerivedField.GetHashCode();
        hash = hash * 31 + BaseField.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("DerivedOpenStruct_Unknown (");
      using (printer.IndentCookie()) {
        printer.Print("derivedField = "); DerivedField.PrintEx(printer); printer.Println();
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:113</p>
  /// </summary>
  public sealed class DerivedStruct : BaseStruct
  {
    //fields
    //public fields
    public bool DerivedField {get; private set;}
    
    //private fields
    //primary constructor
    public DerivedStruct(
      bool derivedField,
      int baseField
    ) : base (
      baseField
     ) 
    {
      DerivedField = derivedField;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<DerivedStruct> Read = (ctx, reader) => 
    {
      var baseField = reader.ReadInt();
      var derivedField = reader.ReadBool();
      var _result = new DerivedStruct(derivedField, baseField);
      return _result;
    };
    
    public static new CtxWriteDelegate<DerivedStruct> Write = (ctx, writer, value) => 
    {
      writer.Write(value.BaseField);
      writer.Write(value.DerivedField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((DerivedStruct) obj);
    }
    public bool Equals(DerivedStruct other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return DerivedField == other.DerivedField && BaseField == other.BaseField;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + DerivedField.GetHashCode();
        hash = hash * 31 + BaseField.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("DerivedStruct (");
      using (printer.IndentCookie()) {
        printer.Print("derivedField = "); DerivedField.PrintEx(printer); printer.Println();
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:143</p>
  /// </summary>
  public sealed class DerivedStructWith2Interfaces : BaseStruct, Interface, Interface2
  {
    //fields
    //public fields
    public bool DerivedField {get; private set;}
    
    //private fields
    //primary constructor
    public DerivedStructWith2Interfaces(
      bool derivedField,
      int baseField
    ) : base (
      baseField
     ) 
    {
      DerivedField = derivedField;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<DerivedStructWith2Interfaces> Read = (ctx, reader) => 
    {
      var baseField = reader.ReadInt();
      var derivedField = reader.ReadBool();
      var _result = new DerivedStructWith2Interfaces(derivedField, baseField);
      return _result;
    };
    
    public static new CtxWriteDelegate<DerivedStructWith2Interfaces> Write = (ctx, writer, value) => 
    {
      writer.Write(value.BaseField);
      writer.Write(value.DerivedField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((DerivedStructWith2Interfaces) obj);
    }
    public bool Equals(DerivedStructWith2Interfaces other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return DerivedField == other.DerivedField && BaseField == other.BaseField;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + DerivedField.GetHashCode();
        hash = hash * 31 + BaseField.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("DerivedStructWith2Interfaces (");
      using (printer.IndentCookie()) {
        printer.Print("derivedField = "); DerivedField.PrintEx(printer); printer.Println();
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:162</p>
  /// </summary>
  public sealed class Document : RdBindableBase
  {
    //fields
    //public fields
    [NotNull] public FooBar Moniker {get; private set;}
    [CanBeNull] public string Buffer {get; private set;}
    [NotNull] public IRdEndpoint<string, int> AndBackAgain => _AndBackAgain;
    [NotNull] public org.example.Completion Completion {get; private set;}
    [NotNull] public byte[] Arr1 {get; private set;}
    [NotNull] public bool[][] Arr2 {get; private set;}
    
    //private fields
    [NotNull] private readonly RdCall<string, int> _AndBackAgain;
    
    //primary constructor
    private Document(
      [NotNull] FooBar moniker,
      [CanBeNull] string buffer,
      [NotNull] RdCall<string, int> andBackAgain,
      [NotNull] org.example.Completion completion,
      [NotNull] byte[] arr1,
      [NotNull] bool[][] arr2
    )
    {
      if (moniker == null) throw new ArgumentNullException("moniker");
      if (andBackAgain == null) throw new ArgumentNullException("andBackAgain");
      if (completion == null) throw new ArgumentNullException("completion");
      if (arr1 == null) throw new ArgumentNullException("arr1");
      if (arr2 == null) throw new ArgumentNullException("arr2");
      
      Moniker = moniker;
      Buffer = buffer;
      _AndBackAgain = andBackAgain;
      Completion = completion;
      Arr1 = arr1;
      Arr2 = arr2;
      BindableChildren.Add(new KeyValuePair<string, object>("moniker", Moniker));
      BindableChildren.Add(new KeyValuePair<string, object>("andBackAgain", _AndBackAgain));
      BindableChildren.Add(new KeyValuePair<string, object>("completion", Completion));
    }
    //secondary constructor
    public Document (
      [NotNull] FooBar moniker,
      [CanBeNull] string buffer,
      [NotNull] byte[] arr1,
      [NotNull] bool[][] arr2
    ) : this (
      moniker,
      buffer,
      new RdCall<string, int>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt),
      new org.example.Completion(),
      arr1,
      arr2
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<Document> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var moniker = FooBar.Read(ctx, reader);
      var buffer = ReadStringNullable(ctx, reader);
      var andBackAgain = RdCall<string, int>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt);
      var completion = org.example.Completion.Read(ctx, reader);
      var arr1 = JetBrains.Rd.Impl.Serializers.ReadByteArray(ctx, reader);
      var arr2 = ReadBoolArrayArray(ctx, reader);
      var _result = new Document(moniker, buffer, andBackAgain, completion, arr1, arr2).WithId(_id);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    public static CtxReadDelegate<bool[][]> ReadBoolArrayArray = JetBrains.Rd.Impl.Serializers.ReadBoolArray.Array();
    
    public static CtxWriteDelegate<Document> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      FooBar.Write(ctx, writer, value.Moniker);
      WriteStringNullable(ctx, writer, value.Buffer);
      RdCall<string, int>.Write(ctx, writer, value._AndBackAgain);
      org.example.Completion.Write(ctx, writer, value.Completion);
      JetBrains.Rd.Impl.Serializers.WriteByteArray(ctx, writer, value.Arr1);
      WriteBoolArrayArray(ctx, writer, value.Arr2);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    public static  CtxWriteDelegate<bool[][]> WriteBoolArrayArray = JetBrains.Rd.Impl.Serializers.WriteBoolArray.Array();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("Document (");
      using (printer.IndentCookie()) {
        printer.Print("moniker = "); Moniker.PrintEx(printer); printer.Println();
        printer.Print("buffer = "); Buffer.PrintEx(printer); printer.Println();
        printer.Print("andBackAgain = "); _AndBackAgain.PrintEx(printer); printer.Println();
        printer.Print("completion = "); Completion.PrintEx(printer); printer.Println();
        printer.Print("arr1 = "); Arr1.PrintEx(printer); printer.Println();
        printer.Print("arr2 = "); Arr2.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:27</p>
  /// </summary>
  [Flags]
  public enum EnumSetTest {
    a = 1 << 0,
    b = 1 << 1,
    c = 1 << 2
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:35</p>
  /// </summary>
  public abstract class Foo : RdBindableBase
  {
    //fields
    //public fields
    public int X {get; private set;}
    [NotNull] public IViewableMap<int, int> Sdf => _Sdf;
    
    //private fields
    [NotNull] protected readonly RdMap<int, int> _Sdf;
    
    //primary constructor
    protected Foo(
      int x,
      [NotNull] RdMap<int, int> sdf
    )
    {
      if (sdf == null) throw new ArgumentNullException("sdf");
      
      X = x;
      _Sdf = sdf;
      _Sdf.OptimizeNested = true;
      BindableChildren.Add(new KeyValuePair<string, object>("sdf", _Sdf));
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<Foo> Read = Polymorphic<Foo>.ReadAbstract(Foo_Unknown.Read);
    
    public static CtxWriteDelegate<Foo> Write = Polymorphic<Foo>.Write;
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    //toString
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:76</p>
  /// </summary>
  public sealed class FooBar : RdBindableBase
  {
    //fields
    //public fields
    [NotNull] public Baz A {get; private set;}
    
    //private fields
    //primary constructor
    public FooBar(
      [NotNull] Baz a
    )
    {
      if (a == null) throw new ArgumentNullException("a");
      
      A = a;
      BindableChildren.Add(new KeyValuePair<string, object>("a", A));
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<FooBar> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var a = Baz.Read(ctx, reader);
      var _result = new FooBar(a).WithId(_id);
      return _result;
    };
    
    public static CtxWriteDelegate<FooBar> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      Baz.Write(ctx, writer, value.A);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("FooBar (");
      using (printer.IndentCookie()) {
        printer.Print("a = "); A.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  public sealed class Foo_Unknown : Foo
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    private Foo_Unknown(
      int x,
      [NotNull] RdMap<int, int> sdf
    ) : base (
      x,
      sdf
     ) 
    {
    }
    //secondary constructor
    public Foo_Unknown (
      int x
    ) : this (
      x,
      new RdMap<int, int>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt)
    ) {}
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<Foo_Unknown> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var x = reader.ReadInt();
      var sdf = RdMap<int, int>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt);
      var _result = new Foo_Unknown(x, sdf).WithId(_id);
      return _result;
    };
    
    public static new CtxWriteDelegate<Foo_Unknown> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      writer.Write(value.X);
      RdMap<int, int>.Write(ctx, writer, value._Sdf);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("Foo_Unknown (");
      using (printer.IndentCookie()) {
        printer.Print("x = "); X.PrintEx(printer); printer.Println();
        printer.Print("sdf = "); _Sdf.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:81</p>
  /// </summary>
  public interface Interface
  {
  }
  
  /// <summary>
  /// <p>Generated from: Example.kt:84</p>
  /// </summary>
  public interface Interface2
  {
  }
  
  /// <summary>
  /// <p>Generated from: Example.kt:101</p>
  /// </summary>
  public class OpenClass : RdBindableBase
  {
    //fields
    //public fields
    public int BaseField {get; private set;}
    
    //private fields
    //primary constructor
    public OpenClass(
      int baseField
    )
    {
      BaseField = baseField;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<OpenClass> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var baseField = reader.ReadInt();
      var _result = new OpenClass(baseField).WithId(_id);
      return _result;
    };
    
    public static CtxWriteDelegate<OpenClass> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      writer.Write(value.BaseField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("OpenClass (");
      using (printer.IndentCookie()) {
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  public sealed class OpenClass_Unknown : OpenClass
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    public OpenClass_Unknown(
      int baseField
    ) : base (
      baseField
     ) 
    {
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<OpenClass_Unknown> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var baseField = reader.ReadInt();
      var _result = new OpenClass_Unknown(baseField).WithId(_id);
      return _result;
    };
    
    public static new CtxWriteDelegate<OpenClass_Unknown> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      writer.Write(value.BaseField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("OpenClass_Unknown (");
      using (printer.IndentCookie()) {
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:105</p>
  /// </summary>
  public class OpenStruct{
    //fields
    //public fields
    public int BaseField {get; private set;}
    
    //private fields
    //primary constructor
    public OpenStruct(
      int baseField
    )
    {
      BaseField = baseField;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<OpenStruct> Read = (ctx, reader) => 
    {
      var baseField = reader.ReadInt();
      var _result = new OpenStruct(baseField);
      return _result;
    };
    
    public static CtxWriteDelegate<OpenStruct> Write = (ctx, writer, value) => 
    {
      writer.Write(value.BaseField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((OpenStruct) obj);
    }
    public bool Equals(OpenStruct other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return BaseField == other.BaseField;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + BaseField.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public virtual void Print(PrettyPrinter printer)
    {
      printer.Println("OpenStruct (");
      using (printer.IndentCookie()) {
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  public sealed class OpenStruct_Unknown : OpenStruct
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    public OpenStruct_Unknown(
      int baseField
    ) : base (
      baseField
     ) 
    {
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<OpenStruct_Unknown> Read = (ctx, reader) => 
    {
      var baseField = reader.ReadInt();
      var _result = new OpenStruct_Unknown(baseField);
      return _result;
    };
    
    public static new CtxWriteDelegate<OpenStruct_Unknown> Write = (ctx, writer, value) => 
    {
      writer.Write(value.BaseField);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((OpenStruct_Unknown) obj);
    }
    public bool Equals(OpenStruct_Unknown other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return BaseField == other.BaseField;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + BaseField.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("OpenStruct_Unknown (");
      using (printer.IndentCookie()) {
        printer.Print("baseField = "); BaseField.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:176</p>
  /// </summary>
  public sealed class ScalarExample : IPrintable, IEquatable<ScalarExample>
  {
    //fields
    //public fields
    public int Intfield {get; private set;}
    
    //private fields
    //primary constructor
    public ScalarExample(
      int intfield
    )
    {
      Intfield = intfield;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out int intfield)
    {
      intfield = Intfield;
    }
    //statics
    
    public static CtxReadDelegate<ScalarExample> Read = (ctx, reader) => 
    {
      var intfield = reader.ReadInt();
      var _result = new ScalarExample(intfield);
      return _result;
    };
    
    public static CtxWriteDelegate<ScalarExample> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Intfield);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ScalarExample) obj);
    }
    public bool Equals(ScalarExample other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Intfield == other.Intfield;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Intfield.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ScalarExample (");
      using (printer.IndentCookie()) {
        printer.Print("intfield = "); Intfield.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:40</p>
  /// </summary>
  public abstract class ScalarPrimer{
    //fields
    //public fields
    public int X {get; private set;}
    
    //private fields
    //primary constructor
    protected ScalarPrimer(
      int x
    )
    {
      X = x;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<ScalarPrimer> Read = Polymorphic<ScalarPrimer>.ReadAbstract(ScalarPrimer_Unknown.Read);
    
    public static CtxWriteDelegate<ScalarPrimer> Write = Polymorphic<ScalarPrimer>.Write;
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    //toString
  }
  
  
  public sealed class ScalarPrimer_Unknown : ScalarPrimer
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    public ScalarPrimer_Unknown(
      int x
    ) : base (
      x
     ) 
    {
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<ScalarPrimer_Unknown> Read = (ctx, reader) => 
    {
      var x = reader.ReadInt();
      var _result = new ScalarPrimer_Unknown(x);
      return _result;
    };
    
    public static new CtxWriteDelegate<ScalarPrimer_Unknown> Write = (ctx, writer, value) => 
    {
      writer.Write(value.X);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ScalarPrimer_Unknown) obj);
    }
    public bool Equals(ScalarPrimer_Unknown other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return X == other.X;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + X.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ScalarPrimer_Unknown (");
      using (printer.IndentCookie()) {
        printer.Print("x = "); X.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:23</p>
  /// </summary>
  public sealed class Selection : IPrintable, IEquatable<Selection>
  {
    //fields
    //public fields
    public int Start {get; private set;}
    public int End {get; private set;}
    [NotNull] public int[] Lst {get; private set;}
    public org.example.EnumSetTest EnumSetTest {get; private set;}
    [NotNull] public string Nls_field {get; private set;}
    
    //private fields
    //primary constructor
    public Selection(
      int start,
      int end,
      [NotNull] int[] lst,
      org.example.EnumSetTest enumSetTest,
      [NotNull] string nls_field
    )
    {
      if (lst == null) throw new ArgumentNullException("lst");
      if (nls_field == null) throw new ArgumentNullException("nls_field");
      
      Start = start;
      End = end;
      Lst = lst;
      EnumSetTest = enumSetTest;
      Nls_field = nls_field;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out int start, out int end, [NotNull] out int[] lst, out org.example.EnumSetTest enumSetTest, [NotNull] out string nls_field)
    {
      start = Start;
      end = End;
      lst = Lst;
      enumSetTest = EnumSetTest;
      nls_field = Nls_field;
    }
    //statics
    
    public static CtxReadDelegate<Selection> Read = (ctx, reader) => 
    {
      var start = reader.ReadInt();
      var end = reader.ReadInt();
      var lst = JetBrains.Rd.Impl.Serializers.ReadIntArray(ctx, reader);
      var enumSetTest = (org.example.EnumSetTest)reader.ReadInt();
      var nls_field = reader.ReadString();
      var _result = new Selection(start, end, lst, enumSetTest, nls_field);
      return _result;
    };
    
    public static CtxWriteDelegate<Selection> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Start);
      writer.Write(value.End);
      JetBrains.Rd.Impl.Serializers.WriteIntArray(ctx, writer, value.Lst);
      writer.Write((int)value.EnumSetTest);
      writer.Write(value.Nls_field);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((Selection) obj);
    }
    public bool Equals(Selection other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Start == other.Start && End == other.End && Lst.SequenceEqual(other.Lst) && EnumSetTest == other.EnumSetTest && Nls_field == other.Nls_field;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Start.GetHashCode();
        hash = hash * 31 + End.GetHashCode();
        hash = hash * 31 + Lst.ContentHashCode();
        hash = hash * 31 + (int) EnumSetTest;
        hash = hash * 31 + Nls_field.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("Selection (");
      using (printer.IndentCookie()) {
        printer.Print("start = "); Start.PrintEx(printer); printer.Println();
        printer.Print("end = "); End.PrintEx(printer); printer.Println();
        printer.Print("lst = "); Lst.PrintEx(printer); printer.Println();
        printer.Print("enumSetTest = "); EnumSetTest.PrintEx(printer); printer.Println();
        printer.Print("nls_field = "); Nls_field.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:90</p>
  /// </summary>
  public sealed class Struct : IPrintable, IEquatable<Struct>
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<Struct> Read = (ctx, reader) => 
    {
      var _result = new Struct();
      return _result;
    };
    
    public static CtxWriteDelegate<Struct> Write = (ctx, writer, value) => 
    {
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((Struct) obj);
    }
    public bool Equals(Struct other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return true;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("Struct (");
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:179</p>
  /// </summary>
  public sealed class TextControl : RdBindableBase
  {
    //fields
    //public fields
    [NotNull] public IReadonlyProperty<org.example.Selection> Selection => _Selection;
    [NotNull] public ISource<Unit> Vsink => _Vsink;
    [NotNull] public void Vsource() => _Vsource.Fire();
    [NotNull] public IRdCall<int, string> There1 => _There1;
    
    //private fields
    [NotNull] private readonly RdProperty<org.example.Selection> _Selection;
    [NotNull] private readonly RdSignal<Unit> _Vsink;
    [NotNull] private readonly RdSignal<Unit> _Vsource;
    [NotNull] private readonly RdCall<int, string> _There1;
    
    //primary constructor
    private TextControl(
      [NotNull] RdProperty<org.example.Selection> selection,
      [NotNull] RdSignal<Unit> vsink,
      [NotNull] RdSignal<Unit> vsource,
      [NotNull] RdCall<int, string> there1
    )
    {
      if (selection == null) throw new ArgumentNullException("selection");
      if (vsink == null) throw new ArgumentNullException("vsink");
      if (vsource == null) throw new ArgumentNullException("vsource");
      if (there1 == null) throw new ArgumentNullException("there1");
      
      _Selection = selection;
      _Vsink = vsink;
      _Vsource = vsource;
      _There1 = there1;
      _Selection.OptimizeNested = true;
      BindableChildren.Add(new KeyValuePair<string, object>("selection", _Selection));
      BindableChildren.Add(new KeyValuePair<string, object>("vsink", _Vsink));
      BindableChildren.Add(new KeyValuePair<string, object>("vsource", _Vsource));
      BindableChildren.Add(new KeyValuePair<string, object>("there1", _There1));
    }
    //secondary constructor
    public TextControl (
    ) : this (
      new RdProperty<org.example.Selection>(org.example.Selection.Read, org.example.Selection.Write),
      new RdSignal<Unit>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid),
      new RdSignal<Unit>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid),
      new RdCall<int, string>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<TextControl> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var selection = RdProperty<org.example.Selection>.Read(ctx, reader, org.example.Selection.Read, org.example.Selection.Write);
      var vsink = RdSignal<Unit>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid);
      var vsource = RdSignal<Unit>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid);
      var there1 = RdCall<int, string>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString);
      var _result = new TextControl(selection, vsink, vsource, there1).WithId(_id);
      return _result;
    };
    
    public static CtxWriteDelegate<TextControl> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      RdProperty<org.example.Selection>.Write(ctx, writer, value._Selection);
      RdSignal<Unit>.Write(ctx, writer, value._Vsink);
      RdSignal<Unit>.Write(ctx, writer, value._Vsource);
      RdCall<int, string>.Write(ctx, writer, value._There1);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("TextControl (");
      using (printer.IndentCookie()) {
        printer.Print("selection = "); _Selection.PrintEx(printer); printer.Println();
        printer.Print("vsink = "); _Vsink.PrintEx(printer); printer.Println();
        printer.Print("vsource = "); _Vsource.PrintEx(printer); printer.Println();
        printer.Print("there1 = "); _There1.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:149</p>
  /// </summary>
  public struct UseStructTest : IPrintable, IEquatable<UseStructTest>
  {
    //fields
    //public fields
    public int TestField {get; private set;}
    [NotNull] public string TestField2 {get; private set;}
    
    //private fields
    //primary constructor
    public UseStructTest(
      int testField,
      [NotNull] string testField2
    )
    {
      if (testField2 == null) throw new ArgumentNullException("testField2");
      
      TestField = testField;
      TestField2 = testField2;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out int testField, [NotNull] out string testField2)
    {
      testField = TestField;
      testField2 = TestField2;
    }
    //statics
    
    public static CtxReadDelegate<UseStructTest> Read = (ctx, reader) => 
    {
      var testField = reader.ReadInt();
      var testField2 = reader.ReadString();
      var _result = new UseStructTest(testField, testField2);
      return _result;
    };
    
    public static CtxWriteDelegate<UseStructTest> Write = (ctx, writer, value) => 
    {
      writer.Write(value.TestField);
      writer.Write(value.TestField2);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((UseStructTest) obj);
    }
    public bool Equals(UseStructTest other)
    {
      return TestField == other.TestField && TestField2 == other.TestField2;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + TestField.GetHashCode();
        hash = hash * 31 + TestField2.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("UseStructTest (");
      using (printer.IndentCookie()) {
        printer.Print("testField = "); TestField.PrintEx(printer); printer.Println();
        printer.Print("testField2 = "); TestField2.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:147</p>
  /// </summary>
  public struct ValueStruct : IPrintable, IEquatable<ValueStruct>
  {
    //fields
    //public fields
    public int Value {get; private set;}
    
    //private fields
    //primary constructor
    public ValueStruct(
      int value
    )
    {
      Value = value;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out int value)
    {
      value = Value;
    }
    //statics
    
    public static CtxReadDelegate<ValueStruct> Read = (ctx, reader) => 
    {
      var value = reader.ReadInt();
      var _result = new ValueStruct(value);
      return _result;
    };
    
    public static CtxWriteDelegate<ValueStruct> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Value);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ValueStruct) obj);
    }
    public bool Equals(ValueStruct other)
    {
      return Value == other.Value;
    }
    public static bool operator ==(ValueStruct left, ValueStruct right)
    {
      return left.Equals(right);
    }
    public static bool operator !=(ValueStruct left, ValueStruct right)
    {
      return !left.Equals(right);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Value.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ValueStruct (");
      using (printer.IndentCookie()) {
        printer.Print("value = "); Value.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: Example.kt:46</p>
  /// </summary>
  public enum Z {
    Bar,
    z1
  }
}
