//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "BaseClassWithInterface.Generated.h"


#include "BaseClassWithInterface_Unknown.Generated.h"

#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace org.example {
// companion
// constants
// initializer
void BaseClassWithInterface::initialize()
{
}
// primary ctor
// secondary constructor
// default ctors and dtors
BaseClassWithInterface::BaseClassWithInterface()
{
    initialize();
}
// reader
rd::Wrapper<BaseClassWithInterface> BaseClassWithInterface::readUnknownInstance(rd::SerializationCtx& ctx, rd::Buffer & buffer, rd::RdId const& unknownId, int32_t size)
{
    int32_t objectStartPosition = buffer.get_position();
    auto _id = rd::RdId::read(buffer);
    auto unknownBytes = rd::Buffer::ByteArray(objectStartPosition + size - buffer.get_position());
    buffer.read_byte_array_raw(unknownBytes);
    BaseClassWithInterface_Unknown res{unknownId, unknownBytes};
    withId(res, _id);
    return rd::Wrapper<BaseClassWithInterface_Unknown>(std::move(res));
}
// writer
// virtual init
void BaseClassWithInterface::init(rd::Lifetime lifetime) const
{
    rd::RdBindableBase::init(lifetime);
}
// identify
void BaseClassWithInterface::identify(const rd::Identities &identities, rd::RdId const &id) const
{
    rd::RdBindableBase::identify(identities, id);
}
// getters
// intern
// equals trait
// equality operators
bool operator==(const BaseClassWithInterface &lhs, const BaseClassWithInterface &rhs) {
    return &lhs == &rhs;
}
bool operator!=(const BaseClassWithInterface &lhs, const BaseClassWithInterface &rhs){
    return !(lhs == rhs);
}
// hash code trait
// type name trait
std::string BaseClassWithInterface::type_name() const
{
    return "BaseClassWithInterface";
}
// static type name trait
std::string BaseClassWithInterface::static_type_name()
{
    return "BaseClassWithInterface";
}
// polymorphic to string
std::string BaseClassWithInterface::toString() const
{
    std::string res = "BaseClassWithInterface\n";
    return res;
}
// external to string
std::string to_string(const BaseClassWithInterface & value)
{
    return value.toString();
}
}

#ifdef _MSC_VER
#pragma warning( pop )
#endif

