//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "DerivedBaseClass.Generated.h"


#include "DerivedBaseClass_Unknown.Generated.h"

#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace org.example {
// companion
// constants
// initializer
void DerivedBaseClass::initialize()
{
}
// primary ctor
DerivedBaseClass::DerivedBaseClass(bool derivedField_, int32_t baseField_) :
BaseClass(std::move(baseField_))
,derivedField_(std::move(derivedField_))
{
    initialize();
}
// secondary constructor
// default ctors and dtors
// reader
rd::Wrapper<DerivedBaseClass> DerivedBaseClass::readUnknownInstance(rd::SerializationCtx& ctx, rd::Buffer & buffer, rd::RdId const& unknownId, int32_t size)
{
    int32_t objectStartPosition = buffer.get_position();
    auto _id = rd::RdId::read(buffer);
    auto derivedField_ = buffer.read_bool();
    auto baseField_ = buffer.read_integral<int32_t>();
    auto unknownBytes = rd::Buffer::ByteArray(objectStartPosition + size - buffer.get_position());
    buffer.read_byte_array_raw(unknownBytes);
    DerivedBaseClass_Unknown res{std::move(derivedField_), std::move(baseField_), unknownId, unknownBytes};
    withId(res, _id);
    return rd::Wrapper<DerivedBaseClass_Unknown>(std::move(res));
}
// writer
// virtual init
void DerivedBaseClass::init(rd::Lifetime lifetime) const
{
    rd::RdBindableBase::init(lifetime);
}
// identify
void DerivedBaseClass::identify(const rd::Identities &identities, rd::RdId const &id) const
{
    rd::RdBindableBase::identify(identities, id);
}
// getters
bool const & DerivedBaseClass::get_derivedField() const
{
    return derivedField_;
}
// intern
// equals trait
// equality operators
bool operator==(const DerivedBaseClass &lhs, const DerivedBaseClass &rhs) {
    return &lhs == &rhs;
}
bool operator!=(const DerivedBaseClass &lhs, const DerivedBaseClass &rhs){
    return !(lhs == rhs);
}
// hash code trait
// type name trait
std::string DerivedBaseClass::type_name() const
{
    return "DerivedBaseClass";
}
// static type name trait
std::string DerivedBaseClass::static_type_name()
{
    return "DerivedBaseClass";
}
// polymorphic to string
std::string DerivedBaseClass::toString() const
{
    std::string res = "DerivedBaseClass\n";
    res += "\tderivedField = ";
    res += rd::to_string(derivedField_);
    res += '\n';
    res += "\tbaseField = ";
    res += rd::to_string(baseField_);
    res += '\n';
    return res;
}
// external to string
std::string to_string(const DerivedBaseClass & value)
{
    return value.toString();
}
}

#ifdef _MSC_VER
#pragma warning( pop )
#endif

