//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.11.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "OpenStruct.Generated.h"


#include "OpenStruct_Unknown.Generated.h"

#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace org.example {
// companion
// constants
// initializer
void OpenStruct::initialize()
{
}
// primary ctor
OpenStruct::OpenStruct(int32_t baseField_) :
rd::IPolymorphicSerializable()
,baseField_(std::move(baseField_))
{
    initialize();
}
// secondary constructor
// default ctors and dtors
// reader
rd::Wrapper<OpenStruct> OpenStruct::readUnknownInstance(rd::SerializationCtx& ctx, rd::Buffer & buffer, rd::RdId const& unknownId, int32_t size)
{
    int32_t objectStartPosition = buffer.get_position();
    auto baseField_ = buffer.read_integral<int32_t>();
    auto unknownBytes = rd::Buffer::ByteArray(objectStartPosition + size - buffer.get_position());
    buffer.read_byte_array_raw(unknownBytes);
    OpenStruct_Unknown res{std::move(baseField_), unknownId, unknownBytes};
    return rd::Wrapper<OpenStruct_Unknown>(std::move(res));
}
// writer
// virtual init
// identify
// getters
int32_t const & OpenStruct::get_baseField() const
{
    return baseField_;
}
// intern
// equals trait
// equality operators
bool operator==(const OpenStruct &lhs, const OpenStruct &rhs) {
    if (lhs.type_name() != rhs.type_name()) return false;
    return lhs.equals(rhs);
}
bool operator!=(const OpenStruct &lhs, const OpenStruct &rhs){
    return !(lhs == rhs);
}
// hash code trait
size_t OpenStruct::hashCode() const noexcept
{
    size_t __r = 0;
    __r = __r * 31 + (rd::hash<int32_t>()(get_baseField()));
    return __r;
}
// type name trait
std::string OpenStruct::type_name() const
{
    return "OpenStruct";
}
// static type name trait
std::string OpenStruct::static_type_name()
{
    return "OpenStruct";
}
// polymorphic to string
std::string OpenStruct::toString() const
{
    std::string res = "OpenStruct\n";
    res += "\tbaseField = ";
    res += rd::to_string(baseField_);
    res += '\n';
    return res;
}
// external to string
std::string to_string(const OpenStruct & value)
{
    return value.toString();
}
}

#ifdef _MSC_VER
#pragma warning( pop )
#endif

