//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.10.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "ScalarExample.Generated.h"



#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace org.example {
// companion
// constants
// initializer
void ScalarExample::initialize()
{
}
// primary ctor
ScalarExample::ScalarExample(int32_t intfield_) :
rd::IPolymorphicSerializable()
,intfield_(std::move(intfield_))
{
    initialize();
}
// secondary constructor
// default ctors and dtors
// reader
ScalarExample ScalarExample::read(rd::SerializationCtx& ctx, rd::Buffer & buffer)
{
    auto intfield_ = buffer.read_integral<int32_t>();
    ScalarExample res{std::move(intfield_)};
    return res;
}
// writer
void ScalarExample::write(rd::SerializationCtx& ctx, rd::Buffer& buffer) const
{
    buffer.write_integral(intfield_);
}
// virtual init
// identify
// getters
int32_t const & ScalarExample::get_intfield() const
{
    return intfield_;
}
// intern
// equals trait
bool ScalarExample::equals(rd::ISerializable const& object) const
{
    auto const &other = dynamic_cast<ScalarExample const&>(object);
    if (this == &other) return true;
    if (this->intfield_ != other.intfield_) return false;
    
    return true;
}
// equality operators
bool operator==(const ScalarExample &lhs, const ScalarExample &rhs) {
    if (lhs.type_name() != rhs.type_name()) return false;
    return lhs.equals(rhs);
}
bool operator!=(const ScalarExample &lhs, const ScalarExample &rhs){
    return !(lhs == rhs);
}
// hash code trait
size_t ScalarExample::hashCode() const noexcept
{
    size_t __r = 0;
    __r = __r * 31 + (rd::hash<int32_t>()(get_intfield()));
    return __r;
}
// type name trait
std::string ScalarExample::type_name() const
{
    return "ScalarExample";
}
// static type name trait
std::string ScalarExample::static_type_name()
{
    return "ScalarExample";
}
// polymorphic to string
std::string ScalarExample::toString() const
{
    std::string res = "ScalarExample\n";
    res += "\tintfield = ";
    res += rd::to_string(intfield_);
    res += '\n';
    return res;
}
// external to string
std::string to_string(const ScalarExample & value)
{
    return value.toString();
}
}

#ifdef _MSC_VER
#pragma warning( pop )
#endif

