//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef SCALARPRIMER_UNKNOWN_GENERATED_H
#define SCALARPRIMER_UNKNOWN_GENERATED_H


#include "protocol/Protocol.h"
#include "types/DateTime.h"
#include "impl/RdSignal.h"
#include "impl/RdProperty.h"
#include "impl/RdList.h"
#include "impl/RdSet.h"
#include "impl/RdMap.h"
#include "base/ISerializersOwner.h"
#include "base/IUnknownInstance.h"
#include "serialization/ISerializable.h"
#include "serialization/Polymorphic.h"
#include "serialization/NullableSerializer.h"
#include "serialization/ArraySerializer.h"
#include "serialization/InternedSerializer.h"
#include "serialization/SerializationCtx.h"
#include "serialization/Serializers.h"
#include "ext/RdExtBase.h"
#include "task/RdCall.h"
#include "task/RdEndpoint.h"
#include "task/RdSymmetricCall.h"
#include "std/to_string.h"
#include "std/hash.h"
#include "std/allocator.h"
#include "util/enum.h"
#include "util/gen_util.h"

#include <cstring>
#include <cstdint>
#include <vector>
#include <ctime>

#include "thirdparty.hpp"
#include "instantiations_ExampleRootNova.h"

#include "ScalarPrimer.Generated.h"



#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace org.example {

class ScalarPrimer_Unknown : public ScalarPrimer, public rd::IUnknownInstance {
friend class ScalarPrimer;

private:
    // custom serializers

public:
    // constants

protected:
    // fields
    rd::RdId unknownId_;
    rd::Buffer::ByteArray unknownBytes_;
    

private:
    // initializer
    void initialize();

public:
    // primary ctor
    ScalarPrimer_Unknown(int32_t x_, rd::RdId unknownId_, rd::Buffer::ByteArray unknownBytes_);
    
    // default ctors and dtors
    
    ScalarPrimer_Unknown() = delete;
    
    ScalarPrimer_Unknown(ScalarPrimer_Unknown const &) = default;
    
    ScalarPrimer_Unknown& operator=(ScalarPrimer_Unknown const &) = default;
    
    ScalarPrimer_Unknown(ScalarPrimer_Unknown &&) = default;
    
    ScalarPrimer_Unknown& operator=(ScalarPrimer_Unknown &&) = default;
    
    virtual ~ScalarPrimer_Unknown() = default;
    
    // reader
    static ScalarPrimer_Unknown read(rd::SerializationCtx& ctx, rd::Buffer & buffer);
    
    // writer
    void write(rd::SerializationCtx& ctx, rd::Buffer& buffer) const override;
    
    // virtual init
    
    // identify
    
    // getters
    
    // intern

private:
    // equals trait
    bool equals(rd::ISerializable const& object) const override;

public:
    // equality operators
    friend bool operator==(const ScalarPrimer_Unknown &lhs, const ScalarPrimer_Unknown &rhs);
    friend bool operator!=(const ScalarPrimer_Unknown &lhs, const ScalarPrimer_Unknown &rhs);
    // hash code trait
    size_t hashCode() const noexcept override;
    // type name trait
    std::string type_name() const override;
    // static type name trait
    static std::string static_type_name();

private:
    // polymorphic to string
    std::string toString() const override;

public:
    // external to string
    friend std::string to_string(const ScalarPrimer_Unknown & value);
};

}

// hash code trait
namespace rd {

template <>
struct hash<org.example::ScalarPrimer_Unknown> {
    size_t operator()(const org.example::ScalarPrimer_Unknown & value) const noexcept {
        return value.hashCode();
    }
};

}

#ifdef _MSC_VER
#pragma warning( pop )
#endif



#endif // SCALARPRIMER_UNKNOWN_GENERATED_H
