//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef USESTRUCTTEST_GENERATED_H
#define USESTRUCTTEST_GENERATED_H


#include "protocol/Protocol.h"
#include "types/DateTime.h"
#include "impl/RdSignal.h"
#include "impl/RdProperty.h"
#include "impl/RdList.h"
#include "impl/RdSet.h"
#include "impl/RdMap.h"
#include "base/ISerializersOwner.h"
#include "base/IUnknownInstance.h"
#include "serialization/ISerializable.h"
#include "serialization/Polymorphic.h"
#include "serialization/NullableSerializer.h"
#include "serialization/ArraySerializer.h"
#include "serialization/InternedSerializer.h"
#include "serialization/SerializationCtx.h"
#include "serialization/Serializers.h"
#include "ext/RdExtBase.h"
#include "task/RdCall.h"
#include "task/RdEndpoint.h"
#include "task/RdSymmetricCall.h"
#include "std/to_string.h"
#include "std/hash.h"
#include "std/allocator.h"
#include "util/enum.h"
#include "util/gen_util.h"

#include <cstring>
#include <cstdint>
#include <vector>
#include <ctime>

#include "thirdparty.hpp"
#include "instantiations_ExampleRootNova.h"



#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

/// <summary>
/// <p>Generated from: Example.kt:149</p>
/// </summary>
namespace org.example {

// data
class UseStructTest : public rd::IPolymorphicSerializable {

private:
    // custom serializers

public:
    // constants

protected:
    // fields
    int32_t testField_;
    rd::Wrapper<std::wstring> testField2_;
    

private:
    // initializer
    void initialize();

public:
    // primary ctor
    UseStructTest(int32_t testField_, rd::Wrapper<std::wstring> testField2_);
    
    // deconstruct trait
    #ifdef __cpp_structured_bindings
    template <size_t I>
    decltype(auto) get() const
    {
        if constexpr (I < 0 || I >= 2) static_assert (I < 0 || I >= 2, "I < 0 || I >= 2");
        else if constexpr (I==0)  return static_cast<const int32_t&>(get_testField());
        else if constexpr (I==1)  return static_cast<const std::wstring&>(get_testField2());
    }
    #endif
    
    // default ctors and dtors
    
    UseStructTest() = delete;
    
    UseStructTest(UseStructTest const &) = default;
    
    UseStructTest& operator=(UseStructTest const &) = default;
    
    UseStructTest(UseStructTest &&) = default;
    
    UseStructTest& operator=(UseStructTest &&) = default;
    
    virtual ~UseStructTest() = default;
    
    // reader
    static UseStructTest read(rd::SerializationCtx& ctx, rd::Buffer & buffer);
    
    // writer
    void write(rd::SerializationCtx& ctx, rd::Buffer& buffer) const override;
    
    // virtual init
    
    // identify
    
    // getters
    int32_t const & get_testField() const;
    std::wstring const & get_testField2() const;
    
    // intern

private:
    // equals trait
    bool equals(rd::ISerializable const& object) const override;

public:
    // equality operators
    friend bool operator==(const UseStructTest &lhs, const UseStructTest &rhs);
    friend bool operator!=(const UseStructTest &lhs, const UseStructTest &rhs);
    // hash code trait
    size_t hashCode() const noexcept override;
    // type name trait
    std::string type_name() const override;
    // static type name trait
    static std::string static_type_name();

private:
    // polymorphic to string
    std::string toString() const override;

public:
    // external to string
    friend std::string to_string(const UseStructTest & value);
};

}

// hash code trait
namespace rd {

template <>
struct hash<org.example::UseStructTest> {
    size_t operator()(const org.example::UseStructTest & value) const noexcept {
        return value.hashCode();
    }
};

}

#ifdef __cpp_structured_bindings
// tuple trait
namespace std {

template <>
class tuple_size<org.example::UseStructTest> : public integral_constant<size_t, 2> {};

template <size_t I>
class tuple_element<I, org.example::UseStructTest> {
public:
    using type = decltype (declval<org.example::UseStructTest>().get<I>());
};

}
#endif

#ifdef _MSC_VER
#pragma warning( pop )
#endif



#endif // USESTRUCTTEST_GENERATED_H
