//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace demo
{
  
  
  /// <summary>
  /// <p>Generated from: DemoModel.kt:204</p>
  /// </summary>
  public class InstantHelperExt : DefaultExtBase
  {
    //fields
    //public fields
    [NotNull] public ISignal<int> Checker => _Checker;
    [NotNull] public IViewableProperty<ExtensibleModel> Value => _Value;
    
    //private fields
    [NotNull] private readonly RdSignal<int> _Checker;
    [NotNull] private readonly RdProperty<ExtensibleModel> _Value;
    
    //primary constructor
    internal static InstantHelperExt CreateInternal()
    {
      return new InstantHelperExt();
    }
    
    private InstantHelperExt(
      [NotNull] RdSignal<int> checker,
      [NotNull] RdProperty<ExtensibleModel> value
    )
    {
      if (checker == null) throw new ArgumentNullException("checker");
      if (value == null) throw new ArgumentNullException("value");
      
      _Checker = checker;
      _Value = value;
      BindableChildren.Add(new KeyValuePair<string, object>("checker", _Checker));
      BindableChildren.Add(new KeyValuePair<string, object>("value", _Value));
    }
    //secondary constructor
    private InstantHelperExt (
    ) : this (
      new RdSignal<int>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt),
      new RdProperty<ExtensibleModel>(ExtensibleModel.Read, ExtensibleModel.Write)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    public static Type PointcutType => typeof(InstantExtRoot);
    
    protected override long SerializationHash => 5068647221194057724L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(InstantExtRoot), InstantExtRoot.RegisterDeclaredTypesSerializers);
    }
    
    public InstantHelperExt(Lifetime lifetime, IProtocol protocol) : this()
    {
      var ext = protocol.GetOrCreateExtension(() => this);
      if (!ReferenceEquals(ext, this))
        throw new InvalidOperationException($"Returned ext: {ext} is not equal to {this}");
    }
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("InstantHelperExt (");
      using (printer.IndentCookie()) {
        printer.Print("checker = "); _Checker.PrintEx(printer); printer.Println();
        printer.Print("value = "); _Value.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  public static class InstantExtRootInstantHelperExtEx
  {
    public static InstantHelperExt GetInstantHelperExt(this IProtocol protocol)
    {
      return protocol.GetOrCreateExtension(() => InstantHelperExt.CreateInternal());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: DemoModel.kt:205</p>
  /// </summary>
  public sealed class ExtensibleModel : RdBindableBase
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<ExtensibleModel> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var _result = new ExtensibleModel().WithId(_id);
      return _result;
    };
    
    public static CtxWriteDelegate<ExtensibleModel> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("ExtensibleModel (");
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
