//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace demo
{
  
  
  /// <summary>
  /// <p>Generated from: DemoModel.kt:198</p>
  /// </summary>
  public class InstantExtRoot : DefaultExtBase
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    internal static InstantExtRoot CreateInternal()
    {
      return new InstantExtRoot();
    }
    
    private InstantExtRoot(
    )
    {
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => -7972064396670934268L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(InstantExtRoot), InstantExtRoot.RegisterDeclaredTypesSerializers);
      serializers.RegisterToplevelOnce(typeof(InstantHelperExt), InstantHelperExt.RegisterDeclaredTypesSerializers);
      serializers.RegisterToplevelOnce(typeof(InstantExtModel), InstantExtModel.RegisterDeclaredTypesSerializers);
    }
    
    public InstantExtRoot(Lifetime lifetime, IProtocol protocol) : this()
    {
      var ext = protocol.GetOrCreateExtension(() => this);
      if (!ReferenceEquals(ext, this))
        throw new InvalidOperationException($"Returned ext: {ext} is not equal to {this}");
    }
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("InstantExtRoot (");
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  public static class ProtocolInstantExtRootEx
  {
    public static InstantExtRoot GetInstantExtRoot(this IProtocol protocol)
    {
      return protocol.GetOrCreateExtension(() => InstantExtRoot.CreateInternal());
    }
  }
}
