//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.07.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace Org.TestRoot1
{
  
  
  /// <summary>
  /// <p>Generated from: FactoryFqnTestDataModel.kt:52</p>
  /// </summary>
  public class Solution2 : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdCall<int, MyClass> Get => _Get;
    [NotNull] public IViewableProperty<RdDocumentModel> TestBuffer => _TestBuffer;
    
    //private fields
    [NotNull] private readonly RdCall<int, MyClass> _Get;
    [NotNull] private readonly RdProperty<RdDocumentModel> _TestBuffer;
    
    //primary constructor
    private Solution2(
      [NotNull] RdCall<int, MyClass> get,
      [NotNull] RdProperty<RdDocumentModel> testBuffer
    )
    {
      if (get == null) throw new ArgumentNullException("get");
      if (testBuffer == null) throw new ArgumentNullException("testBuffer");
      
      _Get = get;
      _TestBuffer = testBuffer;
      BindableChildren.Add(new KeyValuePair<string, object>("get", _Get));
      BindableChildren.Add(new KeyValuePair<string, object>("testBuffer", _TestBuffer));
    }
    //secondary constructor
    private Solution2 (
    ) : this (
      new RdCall<int, MyClass>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt, MyClass.Read, MyClass.Write),
      new RdProperty<RdDocumentModel>(RdDocumentModel.Read, RdDocumentModel.Write)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => -4893872890057629939L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(TestRoot1), TestRoot1.RegisterDeclaredTypesSerializers);
    }
    
    public Solution2(Lifetime lifetime, IProtocol protocol) : this()
    {
      Identify(protocol.Identities, RdId.Root.Mix("Solution2"));
      Bind(lifetime, protocol, "Solution2");
    }
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("Solution2 (");
      using (printer.IndentCookie()) {
        printer.Print("get = "); _Get.PrintEx(printer); printer.Println();
        printer.Print("testBuffer = "); _TestBuffer.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: FactoryFqnTestDataModel.kt:59</p>
  /// </summary>
  public sealed class MyClass : RdBindableBase
  {
    //fields
    //public fields
    [NotNull] public IViewableSet<string> MySet => _MySet;
    
    //private fields
    [NotNull] private readonly RdSet<string> _MySet;
    
    //primary constructor
    private MyClass(
      [NotNull] RdSet<string> mySet
    )
    {
      if (mySet == null) throw new ArgumentNullException("mySet");
      
      _MySet = mySet;
      _MySet.OptimizeNested = true;
      BindableChildren.Add(new KeyValuePair<string, object>("mySet", _MySet));
    }
    //secondary constructor
    public MyClass (
    ) : this (
      new RdSet<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<MyClass> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var mySet = RdSet<string>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString);
      var _result = new MyClass(mySet).WithId(_id);
      return _result;
    };
    
    public static CtxWriteDelegate<MyClass> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      RdSet<string>.Write(ctx, writer, value._MySet);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("MyClass (");
      using (printer.IndentCookie()) {
        printer.Print("mySet = "); _MySet.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: FactoryFqnTestDataModel.kt:54</p>
  /// </summary>
  public sealed class RdDocumentModel : RdBindableBase
  {
    //fields
    //public fields
    [NotNull] public JetBrains.Rd.Text.Impl.RdDeferrableTextBuffer Text => _Text;
    
    //private fields
    [NotNull] private readonly JetBrains.Rd.Text.Impl.RdDeferrableTextBuffer _Text;
    
    //primary constructor
    private RdDocumentModel(
      [NotNull] JetBrains.Rd.Text.Impl.RdDeferrableTextBuffer text
    )
    {
      if (text == null) throw new ArgumentNullException("text");
      
      _Text = text;
      BindableChildren.Add(new KeyValuePair<string, object>("text", _Text));
    }
    //secondary constructor
    public RdDocumentModel (
    ) : this (
      new JetBrains.Rd.Text.Impl.RdDeferrableTextBuffer(new JetBrains.Rd.Text.Impl.Intrinsics.RdTextBufferState())
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<RdDocumentModel> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var text = new JetBrains.Rd.Text.Impl.RdDeferrableTextBuffer(JetBrains.Rd.Text.Impl.Intrinsics.RdTextBufferState.Read(ctx, reader));
      var _result = new RdDocumentModel(text).WithId(_id);
      return _result;
    };
    
    public static CtxWriteDelegate<RdDocumentModel> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      JetBrains.Rd.Text.Impl.Intrinsics.RdTextBufferState.Write(ctx, writer, value._Text.Delegate);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("RdDocumentModel (");
      using (printer.IndentCookie()) {
        printer.Print("text = "); _Text.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
