name: rd-net

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: ivanpashchenko/rider-full-debian-stretch-slim:latest
    steps:
    - uses: actions/checkout@v2
    - run: dotnet --version
    - run: cd rd-net && dotnet restore
    - run: cd rd-net && dotnet build --configuration Release --no-restore
    - name: Tests
      run: cd rd-net && dotnet test --no-restore --verbosity quiet --logger trx
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: tests-log
        path: "**/TestResults/*"

