name: QodanaCustomImageJob
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.1.0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: 'Deploy to GitHub Pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ${{ runner.temp }}/qodana/results/
